server {
    listen 8080;
    server_name 192.168.0.30;

    location / {
        proxy_pass http://kafka-ui:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name 192.168.0.30;

    location / {
        proxy_pass http://fastapi_app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name 192.168.0.30;

    ssl_certificate /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

     root /var/www/static;

    location = /.well-known/openid-configuration {
        # Указываем Nginx искать файл openid-configuration.json в директории root
        try_files /openid-configuration.json =404;
        # Разрешаем запросы с любого домена. Для jwt.io это необходимо.
        add_header 'Access-Control-Allow-Origin' '*' always;
        # Добавляем заголовок, чтобы браузеры и клиенты понимали, что это JSON
        add_header Content-Type application/json;
    }

    location = /jwks {
        # Указываем Nginx искать файл jwks.json в директории root
        try_files /jwks.json =404;
        # Разрешаем запросы с любого домена.
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header Content-Type application/json;
    }

    location / {
        proxy_pass http://fastapi_app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}